name: build-deploy-flutter-windows.yml
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-release-android-app:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.4'
      - name: Install Dependencies
        run: flutter pub get
      - name: Build Windows exe
        run: flutter build windows --release
      - name: Release Windows exe
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/x64/runner/Release/flashcard.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



