name: build-deploy-flutter-web.yml
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-web-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.4'
      - name: Install Dependencies
        run: flutter pub get
      - name: Build Web
        # CAUTION: Ensure updating the base-href on changing the repo name
        run: flutter build web --base-href "/flashcard/"
      - name: Upload Web Build Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/web/

  deploy-web-app:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-web-app
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
